openapi: 3.1.0
info:
  title: YapPad
  description: YapPad API allows users to generate stories based on genre and prompts.
  version: 1.0.0
servers:
  - url: https://yappad.vercel.app
paths:
  /API/v1/docs:
    get:
      summary: Get Swagger documentation
      description: Retrieve the Swagger documentation for this API.
      responses:
        "200":
          description: Successful operation
          content:
            text/html:
              schema:
                type: string
                example: |
                  <!DOCTYPE html>
                  <html>
                  <head>
                    <title>Swagger UI</title>
                    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.1.6/swagger-ui.css">
                  </head>
                  <body>
                    <div id="swagger-ui"></div>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.1.6/swagger-ui-bundle.js"></script>
                    <script src="https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/4.1.6/swagger-ui-standalone-preset.js"></script>
                    <script>
                      window.onload = function() {
                        const ui = SwaggerUIBundle({
                          url: "/API/v1/swagger.yaml", // Specify the correct path to your swagger.yaml file
                          dom_id: '#swagger-ui',
                          deepLinking: true,
                          presets: [
                            SwaggerUIBundle.presets.apis,
                            SwaggerUIStandalonePreset
                          ],
                          layout: "BaseLayout",
                          plugins: [
                            SwaggerUIBundle.plugins.DownloadUrl
                          ],
                          operationsSorter: "alpha"
                        })
                      }
                    </script>
                  </body>
                  </html>